import { NextRequest, NextResponse } from 'next/server';
import { requireAuthOrApiKey } from '@/lib/auth-guard';
import { prisma } from '@/lib/prisma';
import archiver from 'archiver';
import { Readable } from 'stream';

export const dynamic = 'force-dynamic';

/**
 * GET /api/projects/[id]/export
 * Export all project artifacts as a ZIP file.
 * Includes code, configs, tests, and documents.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { session, error } = await requireAuthOrApiKey();
    if (error) return error;
    const { id: projectId } = await params;

    // Verify the user is a member of this project
    const membership = await prisma.projectMember.findFirst({
      where: {
        projectId,
        userId: (session.user as any)?.id,
      },
    });

    if (!membership) {
      return NextResponse.json({ error: 'Not a project member' }, { status: 403 });
    }

    // Fetch project info
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      select: { name: true },
    });

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    // Fetch all artifacts
    const artifacts = await prisma.artifact.findMany({
      where: { projectId },
      select: {
        name: true,
        content: true,
        type: true,
        ownerAgent: true,
        version: true,
      },
      orderBy: { name: 'asc' },
    });

    // Fetch documents
    const documents = await prisma.document.findMany({
      where: { projectId },
      select: {
        title: true,
        content: true,
        type: true,
      },
      orderBy: { title: 'asc' },
    });

    // Create ZIP archive in memory
    const archive = archiver('zip', { zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    // Collect archive data
    await new Promise<void>((resolve, reject) => {
      archive.on('data', (chunk: Buffer) => chunks.push(chunk));
      archive.on('end', resolve);
      archive.on('error', reject);

      // Add artifacts to zip
      for (const artifact of artifacts) {
        const path = artifact.name.startsWith('/')
          ? artifact.name.slice(1)
          : artifact.name;
        archive.append(artifact.content, { name: path });
      }

      // Add documents to docs/ folder
      for (const doc of documents) {
        const safeName = doc.title
          .replace(/[^a-zA-Z0-9-_ ]/g, '')
          .replace(/\s+/g, '-')
          .toLowerCase();
        const ext = 'md'; // All document types (BRD, SDD, API_SPEC, RUNBOOK, ADR) are markdown
        archive.append(doc.content, {
          name: `docs/${safeName}.${ext}`,
        });
      }

      // Add a README with project info
      const readmeContent = `# ${project.name}

Generated by Codanium.

## Project Structure

### Code Artifacts (${artifacts.filter((a) => a.type === 'CODE').length} files)
${artifacts
  .filter((a) => a.type === 'CODE')
  .map((a) => `- ${a.name} (by ${a.ownerAgent}, v${a.version})`)
  .join('\n')}

### Config Files (${artifacts.filter((a) => a.type === 'CONFIG').length} files)
${artifacts
  .filter((a) => a.type === 'CONFIG')
  .map((a) => `- ${a.name}`)
  .join('\n')}

### Test Files (${artifacts.filter((a) => a.type === 'TEST').length} files)
${artifacts
  .filter((a) => a.type === 'TEST')
  .map((a) => `- ${a.name}`)
  .join('\n')}

### Documents (${documents.length} files)
${documents.map((d) => `- docs/${d.title}`).join('\n')}

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
`;

      archive.append(readmeContent, { name: 'README.md' });

      archive.finalize();
    });

    const zipBuffer = Buffer.concat(chunks);
    const safeName = project.name
      .replace(/[^a-zA-Z0-9-_ ]/g, '')
      .replace(/\s+/g, '-')
      .toLowerCase();

    return new NextResponse(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${safeName}.zip"`,
        'Content-Length': String(zipBuffer.length),
      },
    });
  } catch (err) {
    console.error('GET /api/projects/[id]/export error:', err);
    return NextResponse.json(
      { error: 'Failed to export project' },
      { status: 500 },
    );
  }
}
